package gpiosingleton
package main














































































}	}		fmt.Println("✓ GPIO[float64] is a singleton")	if gpioFloat == gpioFloat2 {	gpioFloat2 := drivers.GetGPIO[float64]()	}		fmt.Println("✓ GPIO[int] is a singleton")	if gpioInt == gpioInt2 {	gpioInt2 := drivers.GetGPIO[int]()	}		fmt.Println("✓ GPIO[bool] is a singleton")	if gpioBool == gpioBool2 {	gpioBool2 := drivers.GetGPIO[bool]()	fmt.Println("\n=== Singleton Verification ===")	// Verify singletons	fmt.Printf("Float pin %s value: %f\n", pinFloat.ID(), valPinFloat)	valPinFloat, _ := pinFloat.Get()	fmt.Printf("Float pin value: %f\n", valFloat)	valFloat, _ := gpioFloat.Get(7)	gpioFloat.Set(7, 3.14159)	}		log.Fatal(err)	if err != nil {	pinFloat, err := gpioFloat.Pin("ANALOG", 7, 1<<0) // Input	defer gpioFloat.Close()	gpioFloat := drivers.GetGPIO[float64]()	fmt.Println("\n=== GPIO[float64] Example ===")	// Example 3: GPIO with float64 values	fmt.Printf("Int pin %s value: %d\n", pinInt.ID(), valPinInt)	valPinInt, _ := pinInt.Get()	fmt.Printf("Int pin value: %d\n", valInt)	valInt, _ := gpioInt.Get(6)	gpioInt.Set(6, 42)	}		log.Fatal(err)	if err != nil {	pinInt, err := gpioInt.Pin("BUTTON", 6, 1<<0) // Input	defer gpioInt.Close()	gpioInt := drivers.GetGPIO[int]()	fmt.Println("\n=== GPIO[int] Example ===")	// Example 2: GPIO with int values	fmt.Printf("Bool pin %s value: %v\n", pinBool.ID(), val)	val, _ := pinBool.Get()	pinBool.Set(true)	}		log.Fatal(err)	if err != nil {	pinBool, err := gpioBool.Pin("LED", 5, 1<<1) // Output	defer gpioBool.Close()	gpioBool := drivers.GetGPIO[bool]()	fmt.Println("=== GPIO[bool] Example ===")	// Example 1: GPIO with bool values	devices.SetMock(true)	// Enable mock mode for this examplefunc main() {)	"github.com/rustyeddy/devices/drivers"	"github.com/rustyeddy/devices"	"log"	"fmt"import (